# Use the official Node.js image as a base image
FROM node:14.17.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install Tailwind CSS
RUN npm install -D tailwindcss

# Copy the rest of the application code
COPY . .

# Generate Tailwind CSS
RUN npx tailwindcss -i ./app/frontend/src/CSS/tailwindInput.css -o ./app/frontend/src/CSS/tailwindOutput.css

# Expose the port the app runs on
EXPOSE 3000

# Start the application and watch for Tailwind CSS changes
CMD ["sh", "-c", "npx tailwindcss -i ./app/frontend/src/CSS/tailwindInput.css -o ./app/frontend/src/CSS/tailwindOutput.css --watch & npm start"]