name: jest tests

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: install dependencies
              run: npm install

            - name: Go BE folder
              run: cd app/backend

            - name: install BE dependencies
              run: npm install

            - name: Go back root folder
              run: cd ../

            - name: run tests
              run: npm test

