name: jest tests

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: install dependencies
              run: npm install

            - name: install testing
              run: npm install --save @testing-library/react @testing-library/jest-dom @testing-library/user-event jest react-router-dom axios dotenv sinon faker pg


            - name: run tests
              run: npm test

